// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: avast.proto

package com.bean_keeper;

public final class Proto {
    private Proto() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public interface TransactionOrBuilder
            extends com.google.protobuf.MessageLiteOrBuilder {

        // optional string guid = 1;

        /**
         * <code>optional string guid = 1;</code>
         * <p/>
         * <pre>
         * A string containing a transaction GUID: "6ea4f8dd-382f-44a6-bc0a-91f3c6b8216b"
         * </pre>
         */
        boolean hasGuid();

        /**
         * <code>optional string guid = 1;</code>
         * <p/>
         * <pre>
         * A string containing a transaction GUID: "6ea4f8dd-382f-44a6-bc0a-91f3c6b8216b"
         * </pre>
         */
        String getGuid();

        /**
         * <code>optional string guid = 1;</code>
         * <p/>
         * <pre>
         * A string containing a transaction GUID: "6ea4f8dd-382f-44a6-bc0a-91f3c6b8216b"
         * </pre>
         */
        com.google.protobuf.ByteString
        getGuidBytes();

        // optional int64 date = 2;

        /**
         * <code>optional int64 date = 2;</code>
         * <p/>
         * <pre>
         * A date and time of the transaction defined as the number of milliseconds since 1970:
         *   1385045656447
         * </pre>
         */
        boolean hasDate();

        /**
         * <code>optional int64 date = 2;</code>
         * <p/>
         * <pre>
         * A date and time of the transaction defined as the number of milliseconds since 1970:
         *   1385045656447
         * </pre>
         */
        long getDate();

        // optional double value = 3;

        /**
         * <code>optional double value = 3;</code>
         * <p/>
         * <pre>
         * An amount of money transferred by the transaction
         * </pre>
         */
        boolean hasValue();

        /**
         * <code>optional double value = 3;</code>
         * <p/>
         * <pre>
         * An amount of money transferred by the transaction
         * </pre>
         */
        double getValue();

        // optional string kind = 4;

        /**
         * <code>optional string kind = 4;</code>
         * <p/>
         * <pre>
         * A description of the transaction
         * </pre>
         */
        boolean hasKind();

        /**
         * <code>optional string kind = 4;</code>
         * <p/>
         * <pre>
         * A description of the transaction
         * </pre>
         */
        String getKind();

        /**
         * <code>optional string kind = 4;</code>
         * <p/>
         * <pre>
         * A description of the transaction
         * </pre>
         */
        com.google.protobuf.ByteString
        getKindBytes();

        // optional bool deleted = 5;

        /**
         * <code>optional bool deleted = 5;</code>
         * <p/>
         * <pre>
         * If TRUE the transaction is deleted. It mustn’t be neither counted into the account balance nor
         * displayed to the user
         * </pre>
         */
        boolean hasDeleted();

        /**
         * <code>optional bool deleted = 5;</code>
         * <p/>
         * <pre>
         * If TRUE the transaction is deleted. It mustn’t be neither counted into the account balance nor
         * displayed to the user
         * </pre>
         */
        boolean getDeleted();
    }

    public interface AccountDeltaOrBuilder
            extends com.google.protobuf.MessageLiteOrBuilder {

        // repeated .com.bean_keeper.Transaction addedOrModified = 1;

        /**
         * <code>repeated .com.bean_keeper.Transaction addedOrModified = 1;</code>
         * <p/>
         * <pre>
         * Added or modified transactions
         * </pre>
         */
        java.util.List<com.bean_keeper.Proto.Transaction>
        getAddedOrModifiedList();

        /**
         * <code>repeated .com.bean_keeper.Transaction addedOrModified = 1;</code>
         * <p/>
         * <pre>
         * Added or modified transactions
         * </pre>
         */
        com.bean_keeper.Proto.Transaction getAddedOrModified(int index);

        /**
         * <code>repeated .com.bean_keeper.Transaction addedOrModified = 1;</code>
         * <p/>
         * <pre>
         * Added or modified transactions
         * </pre>
         */
        int getAddedOrModifiedCount();

        // optional int64 serverTimestamp = 2;

        /**
         * <code>optional int64 serverTimestamp = 2;</code>
         * <p/>
         * <pre>
         * When sending to the server: The timestamp of the last successful sync with the server.
         * When received from the server: The current server timestamp to be stored as the timestamp of
         *   the last successful sync with the server.
         * The timestamp is defined as the number of milliseconds since 1970.
         * </pre>
         */
        boolean hasServerTimestamp();

        /**
         * <code>optional int64 serverTimestamp = 2;</code>
         * <p/>
         * <pre>
         * When sending to the server: The timestamp of the last successful sync with the server.
         * When received from the server: The current server timestamp to be stored as the timestamp of
         *   the last successful sync with the server.
         * The timestamp is defined as the number of milliseconds since 1970.
         * </pre>
         */
        long getServerTimestamp();
    }

    /**
     * Protobuf type {@code com.bean_keeper.Transaction}
     */
    public static final class Transaction extends
            com.google.protobuf.GeneratedMessageLite
            implements TransactionOrBuilder {
        // optional string guid = 1;
        public static final int GUID_FIELD_NUMBER = 1;
        // optional int64 date = 2;
        public static final int DATE_FIELD_NUMBER = 2;
        // optional double value = 3;
        public static final int VALUE_FIELD_NUMBER = 3;
        // optional string kind = 4;
        public static final int KIND_FIELD_NUMBER = 4;
        // optional bool deleted = 5;
        public static final int DELETED_FIELD_NUMBER = 5;
        private static final Transaction defaultInstance;
        private static final long serialVersionUID = 0L;
        public static com.google.protobuf.Parser<Transaction> PARSER =
                new com.google.protobuf.AbstractParser<Transaction>() {
                    public Transaction parsePartialFrom(
                            com.google.protobuf.CodedInputStream input,
                            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                            throws com.google.protobuf.InvalidProtocolBufferException {
                        return new Transaction(input, extensionRegistry);
                    }
                };
        private int bitField0_;
        private Object guid_;
        private long date_;
        private double value_;
        private Object kind_;
        private boolean deleted_;
        private byte memoizedIsInitialized = -1;
        private int memoizedSerializedSize = -1;

        // Use Transaction.newBuilder() to construct.
        private Transaction(com.google.protobuf.GeneratedMessageLite.Builder builder) {
            super(builder);

        }

        private Transaction(boolean noInit) {
        }

        private Transaction(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            initFields();
            int mutable_bitField0_ = 0;
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!parseUnknownField(input,
                                    extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 10: {
                            bitField0_ |= 0x00000001;
                            guid_ = input.readBytes();
                            break;
                        }
                        case 16: {
                            bitField0_ |= 0x00000002;
                            date_ = input.readInt64();
                            break;
                        }
                        case 25: {
                            bitField0_ |= 0x00000004;
                            value_ = input.readDouble();
                            break;
                        }
                        case 34: {
                            bitField0_ |= 0x00000008;
                            kind_ = input.readBytes();
                            break;
                        }
                        case 40: {
                            bitField0_ |= 0x00000010;
                            deleted_ = input.readBool();
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e.getMessage()).setUnfinishedMessage(this);
            } finally {
                makeExtensionsImmutable();
            }
        }

        public static Transaction getDefaultInstance() {
            return defaultInstance;
        }

        public static com.bean_keeper.Proto.Transaction parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.bean_keeper.Proto.Transaction parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.bean_keeper.Proto.Transaction parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.bean_keeper.Proto.Transaction parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.bean_keeper.Proto.Transaction parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static com.bean_keeper.Proto.Transaction parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static com.bean_keeper.Proto.Transaction parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input);
        }

        public static com.bean_keeper.Proto.Transaction parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input, extensionRegistry);
        }

        public static com.bean_keeper.Proto.Transaction parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static com.bean_keeper.Proto.Transaction parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return Builder.create();
        }

        public static Builder newBuilder(com.bean_keeper.Proto.Transaction prototype) {
            return newBuilder().mergeFrom(prototype);
        }

        public Transaction getDefaultInstanceForType() {
            return defaultInstance;
        }

        @Override
        public com.google.protobuf.Parser<Transaction> getParserForType() {
            return PARSER;
        }

        /**
         * <code>optional string guid = 1;</code>
         * <p/>
         * <pre>
         * A string containing a transaction GUID: "6ea4f8dd-382f-44a6-bc0a-91f3c6b8216b"
         * </pre>
         */
        public boolean hasGuid() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        /**
         * <code>optional string guid = 1;</code>
         * <p/>
         * <pre>
         * A string containing a transaction GUID: "6ea4f8dd-382f-44a6-bc0a-91f3c6b8216b"
         * </pre>
         */
        public String getGuid() {
            Object ref = guid_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    guid_ = s;
                }
                return s;
            }
        }

        /**
         * <code>optional string guid = 1;</code>
         * <p/>
         * <pre>
         * A string containing a transaction GUID: "6ea4f8dd-382f-44a6-bc0a-91f3c6b8216b"
         * </pre>
         */
        public com.google.protobuf.ByteString
        getGuidBytes() {
            Object ref = guid_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                guid_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>optional int64 date = 2;</code>
         * <p/>
         * <pre>
         * A date and time of the transaction defined as the number of milliseconds since 1970:
         *   1385045656447
         * </pre>
         */
        public boolean hasDate() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }

        /**
         * <code>optional int64 date = 2;</code>
         * <p/>
         * <pre>
         * A date and time of the transaction defined as the number of milliseconds since 1970:
         *   1385045656447
         * </pre>
         */
        public long getDate() {
            return date_;
        }

        /**
         * <code>optional double value = 3;</code>
         * <p/>
         * <pre>
         * An amount of money transferred by the transaction
         * </pre>
         */
        public boolean hasValue() {
            return ((bitField0_ & 0x00000004) == 0x00000004);
        }

        /**
         * <code>optional double value = 3;</code>
         * <p/>
         * <pre>
         * An amount of money transferred by the transaction
         * </pre>
         */
        public double getValue() {
            return value_;
        }

        /**
         * <code>optional string kind = 4;</code>
         * <p/>
         * <pre>
         * A description of the transaction
         * </pre>
         */
        public boolean hasKind() {
            return ((bitField0_ & 0x00000008) == 0x00000008);
        }

        /**
         * <code>optional string kind = 4;</code>
         * <p/>
         * <pre>
         * A description of the transaction
         * </pre>
         */
        public String getKind() {
            Object ref = kind_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    kind_ = s;
                }
                return s;
            }
        }

        /**
         * <code>optional string kind = 4;</code>
         * <p/>
         * <pre>
         * A description of the transaction
         * </pre>
         */
        public com.google.protobuf.ByteString
        getKindBytes() {
            Object ref = kind_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                kind_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>optional bool deleted = 5;</code>
         * <p/>
         * <pre>
         * If TRUE the transaction is deleted. It mustn’t be neither counted into the account balance nor
         * displayed to the user
         * </pre>
         */
        public boolean hasDeleted() {
            return ((bitField0_ & 0x00000010) == 0x00000010);
        }

        /**
         * <code>optional bool deleted = 5;</code>
         * <p/>
         * <pre>
         * If TRUE the transaction is deleted. It mustn’t be neither counted into the account balance nor
         * displayed to the user
         * </pre>
         */
        public boolean getDeleted() {
            return deleted_;
        }

        private void initFields() {
            guid_ = "";
            date_ = 0L;
            value_ = 0D;
            kind_ = "";
            deleted_ = false;
        }

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized != -1) return isInitialized == 1;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            getSerializedSize();
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeBytes(1, getGuidBytes());
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                output.writeInt64(2, date_);
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                output.writeDouble(3, value_);
            }
            if (((bitField0_ & 0x00000008) == 0x00000008)) {
                output.writeBytes(4, getKindBytes());
            }
            if (((bitField0_ & 0x00000010) == 0x00000010)) {
                output.writeBool(5, deleted_);
            }
        }

        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1) return size;

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(1, getGuidBytes());
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt64Size(2, date_);
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeDoubleSize(3, value_);
            }
            if (((bitField0_ & 0x00000008) == 0x00000008)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(4, getKindBytes());
            }
            if (((bitField0_ & 0x00000010) == 0x00000010)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBoolSize(5, deleted_);
            }
            memoizedSerializedSize = size;
            return size;
        }

        @Override
        protected Object writeReplace()
                throws java.io.ObjectStreamException {
            return super.writeReplace();
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public Builder toBuilder() {
            return newBuilder(this);
        }

        /**
         * Protobuf type {@code com.bean_keeper.Transaction}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageLite.Builder<
                        com.bean_keeper.Proto.Transaction, Builder>
                implements com.bean_keeper.Proto.TransactionOrBuilder {
            private int bitField0_;
            // optional string guid = 1;
            private Object guid_ = "";
            // optional int64 date = 2;
            private long date_;
            // optional double value = 3;
            private double value_;
            // optional string kind = 4;
            private Object kind_ = "";
            // optional bool deleted = 5;
            private boolean deleted_;

            // Construct using com.bean_keeper.Proto.Transaction.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private static Builder create() {
                return new Builder();
            }

            private void maybeForceBuilderInitialization() {
            }

            public Builder clear() {
                super.clear();
                guid_ = "";
                bitField0_ = (bitField0_ & ~0x00000001);
                date_ = 0L;
                bitField0_ = (bitField0_ & ~0x00000002);
                value_ = 0D;
                bitField0_ = (bitField0_ & ~0x00000004);
                kind_ = "";
                bitField0_ = (bitField0_ & ~0x00000008);
                deleted_ = false;
                bitField0_ = (bitField0_ & ~0x00000010);
                return this;
            }

            public Builder clone() {
                return create().mergeFrom(buildPartial());
            }

            public com.bean_keeper.Proto.Transaction getDefaultInstanceForType() {
                return getDefaultInstance();
            }

            public com.bean_keeper.Proto.Transaction build() {
                com.bean_keeper.Proto.Transaction result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public com.bean_keeper.Proto.Transaction buildPartial() {
                com.bean_keeper.Proto.Transaction result = new com.bean_keeper.Proto.Transaction(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.guid_ = guid_;
                if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                    to_bitField0_ |= 0x00000002;
                }
                result.date_ = date_;
                if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
                    to_bitField0_ |= 0x00000004;
                }
                result.value_ = value_;
                if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
                    to_bitField0_ |= 0x00000008;
                }
                result.kind_ = kind_;
                if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
                    to_bitField0_ |= 0x00000010;
                }
                result.deleted_ = deleted_;
                result.bitField0_ = to_bitField0_;
                return result;
            }

            public Builder mergeFrom(com.bean_keeper.Proto.Transaction other) {
                if (other == getDefaultInstance()) return this;
                if (other.hasGuid()) {
                    bitField0_ |= 0x00000001;
                    guid_ = other.guid_;

                }
                if (other.hasDate()) {
                    setDate(other.getDate());
                }
                if (other.hasValue()) {
                    setValue(other.getValue());
                }
                if (other.hasKind()) {
                    bitField0_ |= 0x00000008;
                    kind_ = other.kind_;

                }
                if (other.hasDeleted()) {
                    setDeleted(other.getDeleted());
                }
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                com.bean_keeper.Proto.Transaction parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (com.bean_keeper.Proto.Transaction) e.getUnfinishedMessage();
                    throw e;
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            /**
             * <code>optional string guid = 1;</code>
             * <p/>
             * <pre>
             * A string containing a transaction GUID: "6ea4f8dd-382f-44a6-bc0a-91f3c6b8216b"
             * </pre>
             */
            public boolean hasGuid() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }

            /**
             * <code>optional string guid = 1;</code>
             * <p/>
             * <pre>
             * A string containing a transaction GUID: "6ea4f8dd-382f-44a6-bc0a-91f3c6b8216b"
             * </pre>
             */
            public String getGuid() {
                Object ref = guid_;
                if (!(ref instanceof String)) {
                    String s = ((com.google.protobuf.ByteString) ref)
                            .toStringUtf8();
                    guid_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <code>optional string guid = 1;</code>
             * <p/>
             * <pre>
             * A string containing a transaction GUID: "6ea4f8dd-382f-44a6-bc0a-91f3c6b8216b"
             * </pre>
             */
            public Builder setGuid(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                guid_ = value;

                return this;
            }

            /**
             * <code>optional string guid = 1;</code>
             * <p/>
             * <pre>
             * A string containing a transaction GUID: "6ea4f8dd-382f-44a6-bc0a-91f3c6b8216b"
             * </pre>
             */
            public com.google.protobuf.ByteString
            getGuidBytes() {
                Object ref = guid_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    guid_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>optional string guid = 1;</code>
             * <p/>
             * <pre>
             * A string containing a transaction GUID: "6ea4f8dd-382f-44a6-bc0a-91f3c6b8216b"
             * </pre>
             */
            public Builder setGuidBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                guid_ = value;

                return this;
            }

            /**
             * <code>optional string guid = 1;</code>
             * <p/>
             * <pre>
             * A string containing a transaction GUID: "6ea4f8dd-382f-44a6-bc0a-91f3c6b8216b"
             * </pre>
             */
            public Builder clearGuid() {
                bitField0_ = (bitField0_ & ~0x00000001);
                guid_ = getDefaultInstance().getGuid();

                return this;
            }

            /**
             * <code>optional int64 date = 2;</code>
             * <p/>
             * <pre>
             * A date and time of the transaction defined as the number of milliseconds since 1970:
             *   1385045656447
             * </pre>
             */
            public boolean hasDate() {
                return ((bitField0_ & 0x00000002) == 0x00000002);
            }

            /**
             * <code>optional int64 date = 2;</code>
             * <p/>
             * <pre>
             * A date and time of the transaction defined as the number of milliseconds since 1970:
             *   1385045656447
             * </pre>
             */
            public long getDate() {
                return date_;
            }

            /**
             * <code>optional int64 date = 2;</code>
             * <p/>
             * <pre>
             * A date and time of the transaction defined as the number of milliseconds since 1970:
             *   1385045656447
             * </pre>
             */
            public Builder setDate(long value) {
                bitField0_ |= 0x00000002;
                date_ = value;

                return this;
            }

            /**
             * <code>optional int64 date = 2;</code>
             * <p/>
             * <pre>
             * A date and time of the transaction defined as the number of milliseconds since 1970:
             *   1385045656447
             * </pre>
             */
            public Builder clearDate() {
                bitField0_ = (bitField0_ & ~0x00000002);
                date_ = 0L;

                return this;
            }

            /**
             * <code>optional double value = 3;</code>
             * <p/>
             * <pre>
             * An amount of money transferred by the transaction
             * </pre>
             */
            public boolean hasValue() {
                return ((bitField0_ & 0x00000004) == 0x00000004);
            }

            /**
             * <code>optional double value = 3;</code>
             * <p/>
             * <pre>
             * An amount of money transferred by the transaction
             * </pre>
             */
            public double getValue() {
                return value_;
            }

            /**
             * <code>optional double value = 3;</code>
             * <p/>
             * <pre>
             * An amount of money transferred by the transaction
             * </pre>
             */
            public Builder setValue(double value) {
                bitField0_ |= 0x00000004;
                value_ = value;

                return this;
            }

            /**
             * <code>optional double value = 3;</code>
             * <p/>
             * <pre>
             * An amount of money transferred by the transaction
             * </pre>
             */
            public Builder clearValue() {
                bitField0_ = (bitField0_ & ~0x00000004);
                value_ = 0D;

                return this;
            }

            /**
             * <code>optional string kind = 4;</code>
             * <p/>
             * <pre>
             * A description of the transaction
             * </pre>
             */
            public boolean hasKind() {
                return ((bitField0_ & 0x00000008) == 0x00000008);
            }

            /**
             * <code>optional string kind = 4;</code>
             * <p/>
             * <pre>
             * A description of the transaction
             * </pre>
             */
            public String getKind() {
                Object ref = kind_;
                if (!(ref instanceof String)) {
                    String s = ((com.google.protobuf.ByteString) ref)
                            .toStringUtf8();
                    kind_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <code>optional string kind = 4;</code>
             * <p/>
             * <pre>
             * A description of the transaction
             * </pre>
             */
            public Builder setKind(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000008;
                kind_ = value;

                return this;
            }

            /**
             * <code>optional string kind = 4;</code>
             * <p/>
             * <pre>
             * A description of the transaction
             * </pre>
             */
            public com.google.protobuf.ByteString
            getKindBytes() {
                Object ref = kind_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    kind_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>optional string kind = 4;</code>
             * <p/>
             * <pre>
             * A description of the transaction
             * </pre>
             */
            public Builder setKindBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000008;
                kind_ = value;

                return this;
            }

            /**
             * <code>optional string kind = 4;</code>
             * <p/>
             * <pre>
             * A description of the transaction
             * </pre>
             */
            public Builder clearKind() {
                bitField0_ = (bitField0_ & ~0x00000008);
                kind_ = getDefaultInstance().getKind();

                return this;
            }

            /**
             * <code>optional bool deleted = 5;</code>
             * <p/>
             * <pre>
             * If TRUE the transaction is deleted. It mustn’t be neither counted into the account balance nor
             * displayed to the user
             * </pre>
             */
            public boolean hasDeleted() {
                return ((bitField0_ & 0x00000010) == 0x00000010);
            }

            /**
             * <code>optional bool deleted = 5;</code>
             * <p/>
             * <pre>
             * If TRUE the transaction is deleted. It mustn’t be neither counted into the account balance nor
             * displayed to the user
             * </pre>
             */
            public boolean getDeleted() {
                return deleted_;
            }

            /**
             * <code>optional bool deleted = 5;</code>
             * <p/>
             * <pre>
             * If TRUE the transaction is deleted. It mustn’t be neither counted into the account balance nor
             * displayed to the user
             * </pre>
             */
            public Builder setDeleted(boolean value) {
                bitField0_ |= 0x00000010;
                deleted_ = value;

                return this;
            }

            /**
             * <code>optional bool deleted = 5;</code>
             * <p/>
             * <pre>
             * If TRUE the transaction is deleted. It mustn’t be neither counted into the account balance nor
             * displayed to the user
             * </pre>
             */
            public Builder clearDeleted() {
                bitField0_ = (bitField0_ & ~0x00000010);
                deleted_ = false;

                return this;
            }

            // @@protoc_insertion_point(builder_scope:com.bean_keeper.Transaction)
        }

        static {
            defaultInstance = new Transaction(true);
            defaultInstance.initFields();
        }

        // @@protoc_insertion_point(class_scope:com.bean_keeper.Transaction)
    }

    /**
     * Protobuf type {@code com.bean_keeper.AccountDelta}
     */
    public static final class AccountDelta extends
            com.google.protobuf.GeneratedMessageLite
            implements AccountDeltaOrBuilder {
        // repeated .com.bean_keeper.Transaction addedOrModified = 1;
        public static final int ADDEDORMODIFIED_FIELD_NUMBER = 1;
        // optional int64 serverTimestamp = 2;
        public static final int SERVERTIMESTAMP_FIELD_NUMBER = 2;
        private static final AccountDelta defaultInstance;
        private static final long serialVersionUID = 0L;
        public static com.google.protobuf.Parser<AccountDelta> PARSER =
                new com.google.protobuf.AbstractParser<AccountDelta>() {
                    public AccountDelta parsePartialFrom(
                            com.google.protobuf.CodedInputStream input,
                            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                            throws com.google.protobuf.InvalidProtocolBufferException {
                        return new AccountDelta(input, extensionRegistry);
                    }
                };
        private int bitField0_;
        private java.util.List<com.bean_keeper.Proto.Transaction> addedOrModified_;
        private long serverTimestamp_;
        private byte memoizedIsInitialized = -1;
        private int memoizedSerializedSize = -1;

        // Use AccountDelta.newBuilder() to construct.
        private AccountDelta(com.google.protobuf.GeneratedMessageLite.Builder builder) {
            super(builder);

        }

        private AccountDelta(boolean noInit) {
        }

        private AccountDelta(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            initFields();
            int mutable_bitField0_ = 0;
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!parseUnknownField(input,
                                    extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 10: {
                            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                                addedOrModified_ = new java.util.ArrayList<com.bean_keeper.Proto.Transaction>();
                                mutable_bitField0_ |= 0x00000001;
                            }
                            addedOrModified_.add(input.readMessage(com.bean_keeper.Proto.Transaction.PARSER, extensionRegistry));
                            break;
                        }
                        case 16: {
                            bitField0_ |= 0x00000001;
                            serverTimestamp_ = input.readInt64();
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e.getMessage()).setUnfinishedMessage(this);
            } finally {
                if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                    addedOrModified_ = java.util.Collections.unmodifiableList(addedOrModified_);
                }
                makeExtensionsImmutable();
            }
        }

        public static AccountDelta getDefaultInstance() {
            return defaultInstance;
        }

        public static com.bean_keeper.Proto.AccountDelta parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.bean_keeper.Proto.AccountDelta parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.bean_keeper.Proto.AccountDelta parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static com.bean_keeper.Proto.AccountDelta parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static com.bean_keeper.Proto.AccountDelta parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static com.bean_keeper.Proto.AccountDelta parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static com.bean_keeper.Proto.AccountDelta parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input);
        }

        public static com.bean_keeper.Proto.AccountDelta parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseDelimitedFrom(input, extensionRegistry);
        }

        public static com.bean_keeper.Proto.AccountDelta parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return PARSER.parseFrom(input);
        }

        public static com.bean_keeper.Proto.AccountDelta parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return PARSER.parseFrom(input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return Builder.create();
        }

        public static Builder newBuilder(com.bean_keeper.Proto.AccountDelta prototype) {
            return newBuilder().mergeFrom(prototype);
        }

        public AccountDelta getDefaultInstanceForType() {
            return defaultInstance;
        }

        @Override
        public com.google.protobuf.Parser<AccountDelta> getParserForType() {
            return PARSER;
        }

        /**
         * <code>repeated .com.bean_keeper.Transaction addedOrModified = 1;</code>
         * <p/>
         * <pre>
         * Added or modified transactions
         * </pre>
         */
        public java.util.List<com.bean_keeper.Proto.Transaction> getAddedOrModifiedList() {
            return addedOrModified_;
        }

        /**
         * <code>repeated .com.bean_keeper.Transaction addedOrModified = 1;</code>
         * <p/>
         * <pre>
         * Added or modified transactions
         * </pre>
         */
        public java.util.List<? extends com.bean_keeper.Proto.TransactionOrBuilder>
        getAddedOrModifiedOrBuilderList() {
            return addedOrModified_;
        }

        /**
         * <code>repeated .com.bean_keeper.Transaction addedOrModified = 1;</code>
         * <p/>
         * <pre>
         * Added or modified transactions
         * </pre>
         */
        public int getAddedOrModifiedCount() {
            return addedOrModified_.size();
        }

        /**
         * <code>repeated .com.bean_keeper.Transaction addedOrModified = 1;</code>
         * <p/>
         * <pre>
         * Added or modified transactions
         * </pre>
         */
        public com.bean_keeper.Proto.Transaction getAddedOrModified(int index) {
            return addedOrModified_.get(index);
        }

        /**
         * <code>repeated .com.bean_keeper.Transaction addedOrModified = 1;</code>
         * <p/>
         * <pre>
         * Added or modified transactions
         * </pre>
         */
        public com.bean_keeper.Proto.TransactionOrBuilder getAddedOrModifiedOrBuilder(
                int index) {
            return addedOrModified_.get(index);
        }

        /**
         * <code>optional int64 serverTimestamp = 2;</code>
         * <p/>
         * <pre>
         * When sending to the server: The timestamp of the last successful sync with the server.
         * When received from the server: The current server timestamp to be stored as the timestamp of
         *   the last successful sync with the server.
         * The timestamp is defined as the number of milliseconds since 1970.
         * </pre>
         */
        public boolean hasServerTimestamp() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }

        /**
         * <code>optional int64 serverTimestamp = 2;</code>
         * <p/>
         * <pre>
         * When sending to the server: The timestamp of the last successful sync with the server.
         * When received from the server: The current server timestamp to be stored as the timestamp of
         *   the last successful sync with the server.
         * The timestamp is defined as the number of milliseconds since 1970.
         * </pre>
         */
        public long getServerTimestamp() {
            return serverTimestamp_;
        }

        private void initFields() {
            addedOrModified_ = java.util.Collections.emptyList();
            serverTimestamp_ = 0L;
        }

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized != -1) return isInitialized == 1;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            getSerializedSize();
            for (int i = 0; i < addedOrModified_.size(); i++) {
                output.writeMessage(1, addedOrModified_.get(i));
            }
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeInt64(2, serverTimestamp_);
            }
        }

        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1) return size;

            size = 0;
            for (int i = 0; i < addedOrModified_.size(); i++) {
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(1, addedOrModified_.get(i));
            }
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt64Size(2, serverTimestamp_);
            }
            memoizedSerializedSize = size;
            return size;
        }

        @Override
        protected Object writeReplace()
                throws java.io.ObjectStreamException {
            return super.writeReplace();
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public Builder toBuilder() {
            return newBuilder(this);
        }

        /**
         * Protobuf type {@code com.bean_keeper.AccountDelta}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageLite.Builder<
                        com.bean_keeper.Proto.AccountDelta, Builder>
                implements com.bean_keeper.Proto.AccountDeltaOrBuilder {
            private int bitField0_;
            // repeated .com.bean_keeper.Transaction addedOrModified = 1;
            private java.util.List<com.bean_keeper.Proto.Transaction> addedOrModified_ =
                    java.util.Collections.emptyList();
            // optional int64 serverTimestamp = 2;
            private long serverTimestamp_;

            // Construct using com.bean_keeper.Proto.AccountDelta.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private static Builder create() {
                return new Builder();
            }

            private void maybeForceBuilderInitialization() {
            }

            public Builder clear() {
                super.clear();
                addedOrModified_ = java.util.Collections.emptyList();
                bitField0_ = (bitField0_ & ~0x00000001);
                serverTimestamp_ = 0L;
                bitField0_ = (bitField0_ & ~0x00000002);
                return this;
            }

            public Builder clone() {
                return create().mergeFrom(buildPartial());
            }

            public com.bean_keeper.Proto.AccountDelta getDefaultInstanceForType() {
                return getDefaultInstance();
            }

            public com.bean_keeper.Proto.AccountDelta build() {
                com.bean_keeper.Proto.AccountDelta result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public com.bean_keeper.Proto.AccountDelta buildPartial() {
                com.bean_keeper.Proto.AccountDelta result = new com.bean_keeper.Proto.AccountDelta(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((bitField0_ & 0x00000001) == 0x00000001)) {
                    addedOrModified_ = java.util.Collections.unmodifiableList(addedOrModified_);
                    bitField0_ = (bitField0_ & ~0x00000001);
                }
                result.addedOrModified_ = addedOrModified_;
                if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.serverTimestamp_ = serverTimestamp_;
                result.bitField0_ = to_bitField0_;
                return result;
            }

            public Builder mergeFrom(com.bean_keeper.Proto.AccountDelta other) {
                if (other == getDefaultInstance()) return this;
                if (!other.addedOrModified_.isEmpty()) {
                    if (addedOrModified_.isEmpty()) {
                        addedOrModified_ = other.addedOrModified_;
                        bitField0_ = (bitField0_ & ~0x00000001);
                    } else {
                        ensureAddedOrModifiedIsMutable();
                        addedOrModified_.addAll(other.addedOrModified_);
                    }

                }
                if (other.hasServerTimestamp()) {
                    setServerTimestamp(other.getServerTimestamp());
                }
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                com.bean_keeper.Proto.AccountDelta parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (com.bean_keeper.Proto.AccountDelta) e.getUnfinishedMessage();
                    throw e;
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private void ensureAddedOrModifiedIsMutable() {
                if (!((bitField0_ & 0x00000001) == 0x00000001)) {
                    addedOrModified_ = new java.util.ArrayList<com.bean_keeper.Proto.Transaction>(addedOrModified_);
                    bitField0_ |= 0x00000001;
                }
            }

            /**
             * <code>repeated .com.bean_keeper.Transaction addedOrModified = 1;</code>
             * <p/>
             * <pre>
             * Added or modified transactions
             * </pre>
             */
            public java.util.List<com.bean_keeper.Proto.Transaction> getAddedOrModifiedList() {
                return java.util.Collections.unmodifiableList(addedOrModified_);
            }

            /**
             * <code>repeated .com.bean_keeper.Transaction addedOrModified = 1;</code>
             * <p/>
             * <pre>
             * Added or modified transactions
             * </pre>
             */
            public int getAddedOrModifiedCount() {
                return addedOrModified_.size();
            }

            /**
             * <code>repeated .com.bean_keeper.Transaction addedOrModified = 1;</code>
             * <p/>
             * <pre>
             * Added or modified transactions
             * </pre>
             */
            public com.bean_keeper.Proto.Transaction getAddedOrModified(int index) {
                return addedOrModified_.get(index);
            }

            /**
             * <code>repeated .com.bean_keeper.Transaction addedOrModified = 1;</code>
             * <p/>
             * <pre>
             * Added or modified transactions
             * </pre>
             */
            public Builder setAddedOrModified(
                    int index, com.bean_keeper.Proto.Transaction value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureAddedOrModifiedIsMutable();
                addedOrModified_.set(index, value);

                return this;
            }

            /**
             * <code>repeated .com.bean_keeper.Transaction addedOrModified = 1;</code>
             * <p/>
             * <pre>
             * Added or modified transactions
             * </pre>
             */
            public Builder setAddedOrModified(
                    int index, com.bean_keeper.Proto.Transaction.Builder builderForValue) {
                ensureAddedOrModifiedIsMutable();
                addedOrModified_.set(index, builderForValue.build());

                return this;
            }

            /**
             * <code>repeated .com.bean_keeper.Transaction addedOrModified = 1;</code>
             * <p/>
             * <pre>
             * Added or modified transactions
             * </pre>
             */
            public Builder addAddedOrModified(com.bean_keeper.Proto.Transaction value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureAddedOrModifiedIsMutable();
                addedOrModified_.add(value);

                return this;
            }

            /**
             * <code>repeated .com.bean_keeper.Transaction addedOrModified = 1;</code>
             * <p/>
             * <pre>
             * Added or modified transactions
             * </pre>
             */
            public Builder addAddedOrModified(
                    int index, com.bean_keeper.Proto.Transaction value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                ensureAddedOrModifiedIsMutable();
                addedOrModified_.add(index, value);

                return this;
            }

            /**
             * <code>repeated .com.bean_keeper.Transaction addedOrModified = 1;</code>
             * <p/>
             * <pre>
             * Added or modified transactions
             * </pre>
             */
            public Builder addAddedOrModified(
                    com.bean_keeper.Proto.Transaction.Builder builderForValue) {
                ensureAddedOrModifiedIsMutable();
                addedOrModified_.add(builderForValue.build());

                return this;
            }

            /**
             * <code>repeated .com.bean_keeper.Transaction addedOrModified = 1;</code>
             * <p/>
             * <pre>
             * Added or modified transactions
             * </pre>
             */
            public Builder addAddedOrModified(
                    int index, com.bean_keeper.Proto.Transaction.Builder builderForValue) {
                ensureAddedOrModifiedIsMutable();
                addedOrModified_.add(index, builderForValue.build());

                return this;
            }

            /**
             * <code>repeated .com.bean_keeper.Transaction addedOrModified = 1;</code>
             * <p/>
             * <pre>
             * Added or modified transactions
             * </pre>
             */
            public Builder addAllAddedOrModified(
                    Iterable<? extends com.bean_keeper.Proto.Transaction> values) {
                ensureAddedOrModifiedIsMutable();
                super.addAll(values, addedOrModified_);

                return this;
            }

            /**
             * <code>repeated .com.bean_keeper.Transaction addedOrModified = 1;</code>
             * <p/>
             * <pre>
             * Added or modified transactions
             * </pre>
             */
            public Builder clearAddedOrModified() {
                addedOrModified_ = java.util.Collections.emptyList();
                bitField0_ = (bitField0_ & ~0x00000001);

                return this;
            }

            /**
             * <code>repeated .com.bean_keeper.Transaction addedOrModified = 1;</code>
             * <p/>
             * <pre>
             * Added or modified transactions
             * </pre>
             */
            public Builder removeAddedOrModified(int index) {
                ensureAddedOrModifiedIsMutable();
                addedOrModified_.remove(index);

                return this;
            }

            /**
             * <code>optional int64 serverTimestamp = 2;</code>
             * <p/>
             * <pre>
             * When sending to the server: The timestamp of the last successful sync with the server.
             * When received from the server: The current server timestamp to be stored as the timestamp of
             *   the last successful sync with the server.
             * The timestamp is defined as the number of milliseconds since 1970.
             * </pre>
             */
            public boolean hasServerTimestamp() {
                return ((bitField0_ & 0x00000002) == 0x00000002);
            }

            /**
             * <code>optional int64 serverTimestamp = 2;</code>
             * <p/>
             * <pre>
             * When sending to the server: The timestamp of the last successful sync with the server.
             * When received from the server: The current server timestamp to be stored as the timestamp of
             *   the last successful sync with the server.
             * The timestamp is defined as the number of milliseconds since 1970.
             * </pre>
             */
            public long getServerTimestamp() {
                return serverTimestamp_;
            }

            /**
             * <code>optional int64 serverTimestamp = 2;</code>
             * <p/>
             * <pre>
             * When sending to the server: The timestamp of the last successful sync with the server.
             * When received from the server: The current server timestamp to be stored as the timestamp of
             *   the last successful sync with the server.
             * The timestamp is defined as the number of milliseconds since 1970.
             * </pre>
             */
            public Builder setServerTimestamp(long value) {
                bitField0_ |= 0x00000002;
                serverTimestamp_ = value;

                return this;
            }

            /**
             * <code>optional int64 serverTimestamp = 2;</code>
             * <p/>
             * <pre>
             * When sending to the server: The timestamp of the last successful sync with the server.
             * When received from the server: The current server timestamp to be stored as the timestamp of
             *   the last successful sync with the server.
             * The timestamp is defined as the number of milliseconds since 1970.
             * </pre>
             */
            public Builder clearServerTimestamp() {
                bitField0_ = (bitField0_ & ~0x00000002);
                serverTimestamp_ = 0L;

                return this;
            }

            // @@protoc_insertion_point(builder_scope:com.bean_keeper.AccountDelta)
        }

        static {
            defaultInstance = new AccountDelta(true);
            defaultInstance.initFields();
        }

        // @@protoc_insertion_point(class_scope:com.bean_keeper.AccountDelta)
    }


    static {
    }

    // @@protoc_insertion_point(outer_class_scope)
}
